## @ingroup Energy-Thermal_Management-Batteries-Heat_Aquisition_Systems
# RCAIDE/Energy/Thermal_Management/Batteries/Heat_Aquisition_Systems/No_Heat_Aquisition.py
# (c) Copyright 2023 Aerospace Research Community LLC 
# 
# Created:  Dec 2023, M. Clarke 

# ----------------------------------------------------------------------------------------------------------------------
#  IMPORT
# ----------------------------------------------------------------------------------------------------------------------
  
from RCAIDE.Energy.Energy_Component import Energy_Component   

# ----------------------------------------------------------------------------------------------------------------------
#  No_Heat_Exchanger
# ----------------------------------------------------------------------------------------------------------------------
## @ingroup Energy-Thermal_Management-Batteries-Heat_Aquisition_Systems
class No_Heat_Aquisition(Energy_Component):
    """This provides output values for a direct convention heat exchanger of a bettery pack
    
    Assumptions:
    None
    
    Source:
    N/A
    """
    
    def __defaults__(self):  
        self.tag   = 'No_Heat_Aquisition'
        return
    def compute_heat_removed(self,battery,Q_heat_gen,T_cell,state,dt,i): 
        '''Computes the net heat generated by the battery pack with no heat exchanger
        heat exchanger
        
        Assumtions:
        None
        
        Source
        None 
        
        Inputs:
        self (heat exchanger) - thermal management system                 [-]
        battery               - battery pack                              [-]
        Q_heat_gen            - thermal load generated by battery         [-]
        numerics              - RCAIDE mission numerics                   [-]
        freestream            - freestream conditions                     [-]
        
        Outputs
        hex_resylts          - battery thermal management system resukts [-]
        '''
         
   
        return hex_results
        
