

 ---------------------------------------------
 Run case  1:   case_0001_0001

 alpha        ->  CL       =   0.4        
 beta         ->  beta        =   0.0
 pb/2V        ->  pb/2V       =   0.0
 qc/2V        ->  qc/2V       =   0.0
 rb/2V        ->  rb/2V       =   0.00000
 flap         ->  flap        =   0.00000
 aileron      ->  Cl roll mom =   0.00000
 elevator     ->  Cm pitchmom =   0.00000
 rudder       ->  Cn yaw  mom =   0.00000

 alpha     =   0.00000     deg
 beta      =   0.00000     deg
 pb/2V     =   0.0
 qc/2V     =   0.0
 rb/2V     =   0.00000
 CL        =   0.4                        
 CDo       =   0.0
 bank      =   0.00000     deg
 elevation =   0.00000     deg
 heading   =   0.00000     deg
 Mach      =   0.159
 velocity  =   0.0     m/s               
 density   =   1.1379     kg/m^3
 grav.acc. =   9.80430458268175     m/s^2
 turn_rad. =   0.00000     m
 load_fac. =   0.00000
 X_cg      =   2.8290812787094772     m
 Y_cg      =   0.0     m
 Z_cg      =   -0.1649037381214625     m
 mass      =   0     kg
 Ixx       =   1258.9771651058988     kg-m^2
 Iyy       =   3386.9310137842053     kg-m^2
 Izz       =   4405.986573078192     kg-m^2
 Ixy       =   104.63052197158453     kg-m^2
 Iyz       =   -14.606353296851742     kg-m^2
 Izx       =   97.49831310209332     kg-m^2
 visc CL_a =   0.00000
 visc CL_u =   0.00000
 visc CM_a =   0.00000
 visc CM_u =   0.00000

