import re


def generate_su2_dataclass(template_path, output_py_path):
    with open(template_path, 'r') as f:
        lines = f.readlines()

    comment_buffer = []
    attributes = []

    # Regex to find (OPT1, OPT2, OPT3) in comments.
    literal_pattern = re.compile(r'\(\s*([A-Za-z0-9_-]+(?:,\s*[A-Za-z0-9_-]+)+)\s*\)')

    for line in lines:
        line = line.strip()

        # Skip truly empty lines or internal source tags
        if not line or line.startswith('[source'):
            continue

        if line.startswith('%'):
            content = line[1:].strip()
            if not content:
                comment_buffer = []
            else:
                comment_buffer.append(content)

        elif '=' in line:
            key, val = line.split('=', 1)
            key = key.strip()
            val = val.strip()

            var_type = "str"
            default_val = f"'{val}'"
            is_bool = False

            # 1. Check for YES/NO directly in the value, or Literal options in the comments
            if val.upper() in ['YES', 'NO']:
                var_type = "bool"
                default_val = "True" if val.upper() == "YES" else "False"
                is_bool = True
            else:
                joined_comments = " ".join(comment_buffer)
                literal_match = literal_pattern.search(joined_comments)

                if literal_match:
                    options = [opt.strip() for opt in literal_match.group(1).split(',')]
                    options_upper = {o.upper() for o in options}

                    if options_upper == {'YES', 'NO'}:
                        var_type = "bool"
                        default_val = "True" if val.upper() == "YES" else "False"
                        is_bool = True
                    elif all(re.match(r'^[A-Za-z0-9_-]+$', o) for o in options):
                        var_type = f"Literal[{', '.join(repr(o) for o in options)}]"

            # 2. Infer Numbers and Tuples if it isn't a boolean
            if var_type == "str" and not is_bool:
                if re.match(r'^-?\d+$', val):
                    var_type = "int"
                    default_val = val

                elif re.match(r'^-?\d*\.\d+([eE][+-]?\d+)?$', val) or re.match(r'^-?\d+[eE][+-]?\d+$', val):
                    var_type = "float"
                    default_val = val

                elif val.startswith('(') and val.endswith(')'):
                    inner = val[1:-1].strip()
                    if not inner:
                        var_type = "tuple"
                        default_val = "()"
                    else:
                        elements = [e.strip() for e in inner.split(',')]
                        elem_types = []
                        parsed_elems = []

                        # Type-check each element inside the tuple
                        for e in elements:
                            if re.match(r'^-?\d+$', e):
                                elem_types.append('int')
                                parsed_elems.append(e)
                            elif re.match(r'^-?\d*\.\d+([eE][+-]?\d+)?$', e) or re.match(r'^-?\d+[eE][+-]?\d+$', e):
                                elem_types.append('float')
                                parsed_elems.append(e)
                            else:
                                elem_types.append('str')
                                parsed_elems.append(f"'{e}'")

                        var_type = f"tuple[{', '.join(elem_types)}]"
                        # Handle Python's trailing comma requirement for single-element tuples
                        if len(parsed_elems) == 1:
                            default_val = f"({parsed_elems[0]},)"
                        else:
                            default_val = f"({', '.join(parsed_elems)})"

            attributes.append((key, var_type, default_val))
            comment_buffer = []

    # 3. Write the generated Dataclass to a Python file
    with open(output_py_path, 'w') as f:
        f.write("from dataclasses import dataclass\n")
        f.write("from typing import Literal\n\n")
        f.write("@dataclass\n")
        f.write("class SU2Config:\n")
        f.write("    \"\"\"Autogenerated SU2 Configuration Dataclass\"\"\"\n")

        for key, vtype, def_val in attributes:
            if def_val == "''":
                f.write(f"    {key}: {vtype} = ''\n")
            else:
                f.write(f"    {key}: {vtype} = {def_val}\n")

        # 4. The Serializer Method
        f.write("\n    def write_to_file(self, filepath: str):\n")
        f.write("        with open(filepath, 'w') as f:\n")
        f.write("            for key, value in self.__dict__.items():\n")
        f.write("                if isinstance(value, bool):\n")
        f.write("                    str_val = 'YES' if value else 'NO'\n")
        f.write("                elif isinstance(value, tuple):\n")
        f.write("                    str_val = '( ' + ', '.join(str(x) for x in value) + ' )'\n")
        f.write("                else:\n")
        f.write("                    str_val = str(value)\n")
        f.write("                f.write(f\"{key}= {str_val}\\n\")\n")

    print(f"Successfully generated {output_py_path} with {len(attributes)} parameters.")

# Example execution:
generate_su2_dataclass('config_template.cfg', 'su2_config_class.py')