## @ingroup Energy-Thermal_Management-Batteries-Heat_Aquisition_Systems
# RCAIDE/Energy/Thermal_Management/Batteries/Heat_Aquisition_Systems/Direct_Air.py
# (c) Copyright 2023 Aerospace Research Community LLC 
# 
# Created:  Dec 2023, M. Clarke 

# ----------------------------------------------------------------------------------------------------------------------
#  IMPORT
# ----------------------------------------------------------------------------------------------------------------------
  
from RCAIDE.Energy.Energy_Component import Energy_Component  
from RCAIDE.Methods.Thermal_Management.Batteries.Performance.Heat_Acquisition_System.Direct_Air_Heat_Aquistion import direct_convection_model
from RCAIDE.Attributes.Gases import Air 

# ----------------------------------------------------------------------------------------------------------------------
#  Atmospheric_Air_Convection_Heat_Exchanger
# ----------------------------------------------------------------------------------------------------------------------
## @ingroup Energy-Thermal_Management-Batteries-Heat_Aquisition_Systems
class Direct_Air(Energy_Component):
    """This provides output values for a direct convention heat exchanger of a bettery pack
    
    Assumptions:
    None
    
    Source:
    N/A
    """
    
    def __defaults__(self):  
        self.tag                                      = 'Atmospheric_Air_Convection_Heat_Exchanger'
        self.cooling_fluid                            = Air()    
        self.cooling_fluid.flowspeed                  = 0.01                                          
        self.convective_heat_transfer_coefficient     = 35.     # [W/m^2K] 
        self.heat_transfer_efficiency                 = 1.0      
        return
    
    def compute_heat_removed(btms,battery,Q_heat_gen,T_cell,state,dt,i): 
        '''Computes the net heat generate by the battery pack with an a direct atmospheric air 
        heat exchanger
        
        Assumtions:
        None
        
        Source
        None 
        
        Inputs:
        self (heat exchanger) - thermal management system                 [-]
        battery               - battery pack                              [-]
        Q_heat_gen            - thermal load generated by battery         [-]
        numerics              - RCAIDE mission numerics                   [-]
        freestream            - freestream conditions                     [-]
        
        Outputs
        hex_resylts          - battery thermal management system resukts [-]
        ''' 
         
        Q_heat_gen_tot, P_net, T_ambient, T_current = direct_convection_model(btms, battery, Q_heat_gen, T_cell, state, dt, i)
         
        return Q_heat_gen_tot, P_net, T_ambient, T_current
        
