

 ---------------------------------------------
 Run case  1:   case_0005_0001

 alpha        ->  CL          =   0.0        
 beta         ->  beta        =   0.0
 pb/2V        ->  pb/2V       =   0.0
 qc/2V        ->  qc/2V       =   0.0
 rb/2V        ->  rb/2V       =   0.00000
 flap         ->  flap        =   0.00000
 aileron      ->  Cl roll mom =   0.00000
 elevator     ->  Cm pitchmom =   0.00000
 rudder       ->  Cn yaw  mom =   0.00000

 alpha     =   0.00000     deg
 beta      =   0.00000     deg
 pb/2V     =   0.0
 qc/2V     =   0.0
 rb/2V     =   0.00000
 CL        =   0.00000                        
 CDo       =   0.0
 bank      =   0.00000     deg
 elevation =   0.00000     deg
 heading   =   0.00000     deg
 Mach      =   0.65
 velocity  =   0.0     m/s               
 density   =   1.225     kg/m^3
 grav.acc. =   9.81     m/s^2
 turn_rad. =   0.00000     m
 load_fac. =   0.00000
 X_cg      =   2.8290812787094772     m
 Y_cg      =   0.0     m
 Z_cg      =   -0.1649037381214625     m
 mass      =   0     kg
 Ixx       =   1274.3305419922824     kg-m^2
 Iyy       =   2948.720771167716     kg-m^2
 Izz       =   3952.4229535753193     kg-m^2
 Ixy       =   104.63052197158453     kg-m^2
 Iyz       =   -14.606353296851742     kg-m^2
 Izx       =   36.188378246297354     kg-m^2
 visc CL_a =   0.00000
 visc CL_u =   0.00000
 visc CM_a =   0.00000
 visc CM_u =   0.00000



 ---------------------------------------------
 Run case  2:   case_0005_0002

 alpha        ->  CL          =   0.0        
 beta         ->  beta        =   0.0
 pb/2V        ->  pb/2V       =   0.0
 qc/2V        ->  qc/2V       =   0.0
 rb/2V        ->  rb/2V       =   0.00000
 flap         ->  flap        =   0.00000
 aileron      ->  Cl roll mom =   0.00000
 elevator     ->  Cm pitchmom =   0.00000
 rudder       ->  Cn yaw  mom =   0.00000

 alpha     =   0.00000     deg
 beta      =   0.00000     deg
 pb/2V     =   0.0
 qc/2V     =   0.0
 rb/2V     =   0.00000
 CL        =   0.00000                        
 CDo       =   0.0
 bank      =   0.00000     deg
 elevation =   0.00000     deg
 heading   =   0.00000     deg
 Mach      =   0.65
 velocity  =   0.0     m/s               
 density   =   1.225     kg/m^3
 grav.acc. =   9.81     m/s^2
 turn_rad. =   0.00000     m
 load_fac. =   0.00000
 X_cg      =   2.8290812787094772     m
 Y_cg      =   0.0     m
 Z_cg      =   -0.1649037381214625     m
 mass      =   0     kg
 Ixx       =   1274.3305419922824     kg-m^2
 Iyy       =   2948.720771167716     kg-m^2
 Izz       =   3952.4229535753193     kg-m^2
 Ixy       =   104.63052197158453     kg-m^2
 Iyz       =   -14.606353296851742     kg-m^2
 Izx       =   36.188378246297354     kg-m^2
 visc CL_a =   0.00000
 visc CL_u =   0.00000
 visc CM_a =   0.00000
 visc CM_u =   0.00000



 ---------------------------------------------
 Run case  3:   case_0005_0003

 alpha        ->  CL          =   0.0        
 beta         ->  beta        =   0.0
 pb/2V        ->  pb/2V       =   0.0
 qc/2V        ->  qc/2V       =   0.0
 rb/2V        ->  rb/2V       =   0.00000
 flap         ->  flap        =   0.00000
 aileron      ->  Cl roll mom =   0.00000
 elevator     ->  Cm pitchmom =   0.00000
 rudder       ->  Cn yaw  mom =   0.00000

 alpha     =   0.00000     deg
 beta      =   0.00000     deg
 pb/2V     =   0.0
 qc/2V     =   0.0
 rb/2V     =   0.00000
 CL        =   0.00000                        
 CDo       =   0.0
 bank      =   0.00000     deg
 elevation =   0.00000     deg
 heading   =   0.00000     deg
 Mach      =   0.65
 velocity  =   0.0     m/s               
 density   =   1.225     kg/m^3
 grav.acc. =   9.81     m/s^2
 turn_rad. =   0.00000     m
 load_fac. =   0.00000
 X_cg      =   2.8290812787094772     m
 Y_cg      =   0.0     m
 Z_cg      =   -0.1649037381214625     m
 mass      =   0     kg
 Ixx       =   1274.3305419922824     kg-m^2
 Iyy       =   2948.720771167716     kg-m^2
 Izz       =   3952.4229535753193     kg-m^2
 Ixy       =   104.63052197158453     kg-m^2
 Iyz       =   -14.606353296851742     kg-m^2
 Izx       =   36.188378246297354     kg-m^2
 visc CL_a =   0.00000
 visc CL_u =   0.00000
 visc CM_a =   0.00000
 visc CM_u =   0.00000



 ---------------------------------------------
 Run case  4:   case_0005_0004

 alpha        ->  CL          =   0.0        
 beta         ->  beta        =   0.0
 pb/2V        ->  pb/2V       =   0.0
 qc/2V        ->  qc/2V       =   0.0
 rb/2V        ->  rb/2V       =   0.00000
 flap         ->  flap        =   0.00000
 aileron      ->  Cl roll mom =   0.00000
 elevator     ->  Cm pitchmom =   0.00000
 rudder       ->  Cn yaw  mom =   0.00000

 alpha     =   0.00000     deg
 beta      =   0.00000     deg
 pb/2V     =   0.0
 qc/2V     =   0.0
 rb/2V     =   0.00000
 CL        =   0.00000                        
 CDo       =   0.0
 bank      =   0.00000     deg
 elevation =   0.00000     deg
 heading   =   0.00000     deg
 Mach      =   0.65
 velocity  =   0.0     m/s               
 density   =   1.225     kg/m^3
 grav.acc. =   9.81     m/s^2
 turn_rad. =   0.00000     m
 load_fac. =   0.00000
 X_cg      =   2.8290812787094772     m
 Y_cg      =   0.0     m
 Z_cg      =   -0.1649037381214625     m
 mass      =   0     kg
 Ixx       =   1274.3305419922824     kg-m^2
 Iyy       =   2948.720771167716     kg-m^2
 Izz       =   3952.4229535753193     kg-m^2
 Ixy       =   104.63052197158453     kg-m^2
 Iyz       =   -14.606353296851742     kg-m^2
 Izx       =   36.188378246297354     kg-m^2
 visc CL_a =   0.00000
 visc CL_u =   0.00000
 visc CM_a =   0.00000
 visc CM_u =   0.00000



 ---------------------------------------------
 Run case  5:   case_0005_0005

 alpha        ->  CL          =   0.0        
 beta         ->  beta        =   0.0
 pb/2V        ->  pb/2V       =   0.0
 qc/2V        ->  qc/2V       =   0.0
 rb/2V        ->  rb/2V       =   0.00000
 flap         ->  flap        =   0.00000
 aileron      ->  Cl roll mom =   0.00000
 elevator     ->  Cm pitchmom =   0.00000
 rudder       ->  Cn yaw  mom =   0.00000

 alpha     =   0.00000     deg
 beta      =   0.00000     deg
 pb/2V     =   0.0
 qc/2V     =   0.0
 rb/2V     =   0.00000
 CL        =   0.00000                        
 CDo       =   0.0
 bank      =   0.00000     deg
 elevation =   0.00000     deg
 heading   =   0.00000     deg
 Mach      =   0.65
 velocity  =   0.0     m/s               
 density   =   1.225     kg/m^3
 grav.acc. =   9.81     m/s^2
 turn_rad. =   0.00000     m
 load_fac. =   0.00000
 X_cg      =   2.8290812787094772     m
 Y_cg      =   0.0     m
 Z_cg      =   -0.1649037381214625     m
 mass      =   0     kg
 Ixx       =   1274.3305419922824     kg-m^2
 Iyy       =   2948.720771167716     kg-m^2
 Izz       =   3952.4229535753193     kg-m^2
 Ixy       =   104.63052197158453     kg-m^2
 Iyz       =   -14.606353296851742     kg-m^2
 Izx       =   36.188378246297354     kg-m^2
 visc CL_a =   0.00000
 visc CL_u =   0.00000
 visc CM_a =   0.00000
 visc CM_u =   0.00000



 ---------------------------------------------
 Run case  6:   case_0005_0006

 alpha        ->  CL          =   0.0        
 beta         ->  beta        =   0.0
 pb/2V        ->  pb/2V       =   0.0
 qc/2V        ->  qc/2V       =   0.0
 rb/2V        ->  rb/2V       =   0.00000
 flap         ->  flap        =   0.00000
 aileron      ->  Cl roll mom =   0.00000
 elevator     ->  Cm pitchmom =   0.00000
 rudder       ->  Cn yaw  mom =   0.00000

 alpha     =   0.00000     deg
 beta      =   0.00000     deg
 pb/2V     =   0.0
 qc/2V     =   0.0
 rb/2V     =   0.00000
 CL        =   0.00000                        
 CDo       =   0.0
 bank      =   0.00000     deg
 elevation =   0.00000     deg
 heading   =   0.00000     deg
 Mach      =   0.65
 velocity  =   0.0     m/s               
 density   =   1.225     kg/m^3
 grav.acc. =   9.81     m/s^2
 turn_rad. =   0.00000     m
 load_fac. =   0.00000
 X_cg      =   2.8290812787094772     m
 Y_cg      =   0.0     m
 Z_cg      =   -0.1649037381214625     m
 mass      =   0     kg
 Ixx       =   1274.3305419922824     kg-m^2
 Iyy       =   2948.720771167716     kg-m^2
 Izz       =   3952.4229535753193     kg-m^2
 Ixy       =   104.63052197158453     kg-m^2
 Iyz       =   -14.606353296851742     kg-m^2
 Izx       =   36.188378246297354     kg-m^2
 visc CL_a =   0.00000
 visc CL_u =   0.00000
 visc CM_a =   0.00000
 visc CM_u =   0.00000

